# Generated by Django 5.0.6 on 2024-07-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderstate_order_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='register_date',
            field=models.DateField(default='1403 04 23', verbose_name='تاریخ درج سفارش'),
        ),
    ]
