# Generated by Django 5.0.6 on 2024-08-20 22:38

import django.db.models.deletion
import django.utils.timezone
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('content', models.TextField(verbose_name='متن اصلی')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر کالا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد مقاله')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزر رسانی')),
                ('published_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ انتشار')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('draft', 'پیش نویس'), ('publish', 'منتشر شده')], default='draft', max_length=100, verbose_name='وضعیت مقاله')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at'],
            },
        ),
    ]
