# Generated by Django 5.0.6 on 2024-08-24 14:17

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_customer_image_name'),
        ('main', '0006_alter_slider_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید '),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع تماس')),
                ('message', models.TextField(verbose_name='پیام تماس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='کاربر تماس گیرنده')),
            ],
        ),
    ]
